# Generated by Django 3.2.8 on 2021-12-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciondirectivoskinder', '0002_auto_20211128_0445'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipodirectivo',
            name='survey_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profesor',
            name='survey_closed',
            field=models.BooleanField(default=False),
        ),
    ]
