# Generated by Django 3.2.8 on 2021-11-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciondirectivos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipodirectivo',
            name='id_survey_profesor_autoevaluacion',
        ),
        migrations.RemoveField(
            model_name='equipodirectivo',
            name='token_profesor_autoevaluacion',
        ),
        migrations.AddField(
            model_name='profesor',
            name='id_survey_profesor_autoevaluacion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='profesor',
            name='token_profesor_autoevaluacion',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
