# Generated by Django 3.2.8 on 2021-10-14 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfesorEvaluado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('materia', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_o_grupo', models.CharField(max_length=300)),
                ('autoevaluacion', models.BooleanField(default=False)),
                ('evaluado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docentes.profesorevaluado')),
            ],
        ),
    ]
