# Generated by Django 3.2.8 on 2021-10-14 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='id_survey',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
