# Generated by Django 3.2.8 on 2021-10-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_evaluador_id_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
