# Generated by Django 3.2.8 on 2021-10-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0003_evaluador_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesorevaluado',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
