# Generated by Django 3.2.8 on 2021-10-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0004_profesorevaluado_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='instrumento_para_alumnos',
            field=models.BooleanField(default=True),
        ),
    ]
