# Generated by Django 3.2.8 on 2021-10-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0007_auto_20211026_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesorevaluado',
            name='id_survey_evaluado',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
