# Generated by Django 3.2.8 on 2021-10-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0008_profesorevaluado_id_survey_evaluado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='token_created',
            field=models.BooleanField(default=False),
        ),
    ]
