# Generated by Django 3.2.8 on 2021-10-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0009_evaluador_token_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluador',
            name='token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
