# Generated by Django 3.2.8 on 2021-11-30 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionalumnosbachillerato', '0002_grupoalumnos_qr_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoalumnos',
            name='qr_survey',
            field=models.ImageField(default='empty', null=True, upload_to='qrs/'),
        ),
    ]
