# Generated by Django 3.2.8 on 2021-10-29 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('materia', models.CharField(max_length=300)),
                ('autoevaluacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoAlumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=300)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacionalumnos.profesor')),
            ],
        ),
    ]
