# Generated by Django 3.2.8 on 2021-10-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionalumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoalumnos',
            name='id_survey',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
