# Generated by Django 3.2.8 on 2021-11-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionalumnos', '0003_auto_20211029_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoalumnos',
            name='response_profesor_autoevaluacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupoalumnos',
            name='response_survey',
            field=models.TextField(blank=True, null=True),
        ),
    ]
