# Generated by Django 3.2.8 on 2021-11-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionalumnos', '0004_auto_20211127_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoalumnos',
            name='response_boolean_profesor_autoevaluacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
