# Generated by Django 3.2.8 on 2021-11-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionalumnos', '0005_grupoalumnos_response_boolean_profesor_autoevaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupoalumnos',
            name='response_boolean_profesor_autoevaluacion',
            field=models.BooleanField(default=False),
        ),
    ]
