# Generated by Django 3.2.8 on 2021-11-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacionalumnos', '0006_alter_grupoalumnos_response_boolean_profesor_autoevaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoalumnos',
            name='response_boolean_survey',
            field=models.BooleanField(default=False),
        ),
    ]
